# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assembly.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(797, 505)
        MainWindow.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"image: url(\"\");")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 1, 4, 3)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QTabBar {\n"
"    background-color: rgb(39, 39, 39);     \n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, stop:0.01 rgb(30, 147, 10), stop:0.15 rgba(255, 255, 255, 0));\n"
"}")
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 4, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setIndent(10)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 2, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setIndent(10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_2.addWidget(self.listWidget_2, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 1, 2, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setContentsMargins(0, 4, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setIndent(10)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 2, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setIndent(10)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_4.setFont(font)
        self.listWidget_4.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_3.addWidget(self.listWidget_4, 1, 0, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_3.addWidget(self.listWidget_3, 1, 2, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/version2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setContentsMargins(0, 4, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setIndent(10)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setIndent(10)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.listWidget_6 = QtWidgets.QListWidget(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_6.setFont(font)
        self.listWidget_6.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_6.setObjectName("listWidget_6")
        self.gridLayout_4.addWidget(self.listWidget_6, 1, 0, 1, 1)
        self.listWidget_5 = QtWidgets.QListWidget(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_5.setFont(font)
        self.listWidget_5.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_5.setObjectName("listWidget_5")
        self.gridLayout_4.addWidget(self.listWidget_5, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(80)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 1, 2, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/curseforge.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(6, 18, -1, -1)
        self.gridLayout_5.setHorizontalSpacing(4)
        self.gridLayout_5.setVerticalSpacing(11)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 5)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 7, 0, 1, 5)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setMinimumSize(QtCore.QSize(99, 30))
        self.comboBox_3.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 14px;\n"
"    margin: -4px 2 -4px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(255, 255, 255, 0);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: rgba(0, 0, 0, 80);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: rgba(49, 49, 49, 140);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(res/open.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 0px;\n"
"    left: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: none;\n"
"    border: 3px solid rgba(30, 30, 30);\n"
"    selection-background-color: rgba(255, 255, 255, 20);\n"
"    border-radius: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(59, 59, 59);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-bottom: 5px;\n"
"}")
        self.comboBox_3.setIconSize(QtCore.QSize(39, 24))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_5.addWidget(self.comboBox_3, 9, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(99, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 14px;\n"
"    margin: -4px 2 -4px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: rgba(0, 0, 0, 80);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: rgba(49, 49, 49, 140);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(res/open.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 0px;\n"
"    left: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: none;\n"
"    border: 3px solid rgba(30, 30, 30);\n"
"    selection-background-color: rgba(255, 255, 255, 20);\n"
"    border-radius: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(59, 59, 59);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-bottom: 5px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_5.addWidget(self.comboBox, 3, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(99, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 14px;\n"
"    margin: -4px 2 -4px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: rgba(0, 0, 0, 80);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: rgba(49, 49, 49, 140);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(res/open.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 0px;\n"
"    left: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: none;\n"
"    border: 3px solid rgba(30, 30, 30);\n"
"    selection-background-color: rgba(255, 255, 255, 20);\n"
"    border-radius: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(59, 59, 59);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-bottom: 5px;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_5.addWidget(self.comboBox_2, 5, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 10, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(96, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(85, 170, 0, 94);\n"
"border-radius: 6px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 11, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMinimumSize(QtCore.QSize(5, 0))
        self.label_14.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 9, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 4, 0, 1, 5)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 5)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setMinimumSize(QtCore.QSize(35, 0))
        self.label_15.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 9, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(96, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(170, 0, 0, 124);\n"
"border-radius: 6px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 11, 1, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(49, 49, 49);\n"
"border-radius: 10px;\n"
"color: rgb(230, 230, 230);")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 0, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Сборка"))
        self.label.setText(_translate("MainWindow", "←\n"
"→"))
        self.label_6.setText(_translate("MainWindow", "Шейдеры"))
        self.label_9.setText(_translate("MainWindow", "Сборка"))
        self.label_8.setText(_translate("MainWindow", "←\n"
"→"))
        self.label_10.setText(_translate("MainWindow", "Текстуры"))
        self.label_12.setText(_translate("MainWindow", "Сборка"))
        self.label_13.setText(_translate("MainWindow", "Моды"))
        self.label_11.setText(_translate("MainWindow", "←\n"
"→"))
        self.label_3.setText(_translate("MainWindow", "Название"))
        self.label_5.setText(_translate("MainWindow", "Иконка"))
        self.pushButton.setText(_translate("MainWindow", "Создать"))
        self.label_4.setText(_translate("MainWindow", "Цвет"))
        self.label_2.setText(_translate("MainWindow", "Версия"))
        self.pushButton_2.setText(_translate("MainWindow", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
