# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maincraft.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 600)
        MainWindow.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setIndent(12)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar {\n"
"    background-color: rgb(39, 39, 39);     \n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, stop:0.01 rgb(30, 147, 10), stop:0.15 rgba(255, 255, 255, 0));\n"
"}")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setMinimumSize(QtCore.QSize(208, 35))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("image: url();\n"
"background-color: rgb(0, 0, 0, 130);\n"
"color: rgb(240, 255, 255);\n"
"border-radius: 8px;")
        self.label_5.setIndent(13)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 2, 3, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setMinimumSize(QtCore.QSize(559, 307))
        self.listWidget.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_6.addWidget(self.listWidget, 0, 4, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_5.setStyleSheet("border-image: url();\n"
"background-color: rgb(0, 0, 0, 60);\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 0, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem6, 2, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(17, 14, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_2.setMinimumSize(QtCore.QSize(99, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 14px;\n"
"    margin: -4px 2 -4px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: rgba(0, 0, 0, 80);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: rgba(49, 49, 49, 140);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(C:/Users/студент.BestLaptop-ПК/Desktop/лаунчер/res/open.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 0px;\n"
"    left: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: none;\n"
"    border: 3px solid rgba(30, 30, 30);\n"
"    selection-background-color: rgba(255, 255, 255, 20);\n"
"    border-radius: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(59, 59, 59);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-bottom: 5px;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_8.addWidget(self.comboBox_2, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 0, 2, 3, 1)
        spacerItem9 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 4, 3, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setMinimumSize(QtCore.QSize(208, 53))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(85, 170, 0, 94);\n"
"border-radius: 9px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_8.addWidget(self.pushButton_4, 0, 3, 3, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/bell.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_8.addWidget(self.pushButton_5, 0, 5, 3, 1)
        self.gridLayout_6.addWidget(self.frame_5, 4, 1, 1, 4)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_13.setContentsMargins(11, 6, 11, 0)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("background-color: rgb(0, 0, 0, 130);\n"
"color: rgb(240, 255, 255);\n"
"border-radius: 15px;\n"
"border-image: url();\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_11.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_11.addWidget(self.pushButton_16, 1, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_17.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_17.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/reboot.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_17.setIcon(icon1)
        self.pushButton_17.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_11.addWidget(self.pushButton_17, 1, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("image: url();\n"
"color: rgb(240, 255, 255);\n"
"background-color: rgb(0, 0, 0, 0);")
        self.label_4.setIndent(13)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 1, 1, 5)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_9.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/старт.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_11.addWidget(self.pushButton_9, 1, 4, 1, 1)
        self.gridLayout_13.addWidget(self.frame_8, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setStyleSheet("border-image: url();\n"
"background-color: rgb(0, 0, 0, 110);\n"
"color: rgb(240, 255, 255);\n"
"border-radius: 15px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_19.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_19.setIcon(icon3)
        self.pushButton_19.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_14.addWidget(self.pushButton_19, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"image: url();")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 1, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"image: url();")
        self.label_6.setIndent(13)
        self.label_6.setObjectName("label_6")
        self.gridLayout_14.addWidget(self.label_6, 0, 1, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem11, 2, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_7.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/version2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_14.addWidget(self.pushButton_7, 0, 5, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_8.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/version.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_14.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_6.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/curseforge.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_14.addWidget(self.pushButton_6, 0, 6, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_14.addWidget(self.pushButton_11, 2, 6, 1, 1)
        self.gridLayout_13.addWidget(self.frame_9, 1, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(19, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem12, 6, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem13, 0, 0, 1, 3)
        spacerItem14 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem14, 7, 0, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem15, 2, 0, 1, 3)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"    background: rgba(255, 255, 255, 29);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_13.addWidget(self.listWidget_2, 6, 2, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"    background: rgba(255, 255, 255, 29);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.listWidget_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_13.addWidget(self.listWidget_3, 5, 0, 2, 1)
        self.gridLayout_10.addWidget(self.frame, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setStyleSheet("background-color: rgba(52, 52, 52);\n"
"color: rgb(240, 255, 255);")
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.tab_5)
        self.frame_4.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QTextBrowser {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout.addWidget(self.textBrowser_3, 0, 1, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_4.setFont(font)
        self.listWidget_4.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"    background: rgba(255, 255, 255, 29);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout.addWidget(self.listWidget_4, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_4, 0, 0, 9, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setMinimumSize(QtCore.QSize(40, 40))
        self.label_9.setMaximumSize(QtCore.QSize(33, 40))
        self.label_9.setStyleSheet("image: url(res/version2.png);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_9.setText("")
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 1, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_23.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_23.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_12.addWidget(self.pushButton_23, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_5)
        self.line_2.setMinimumSize(QtCore.QSize(0, 7))
        self.line_2.setLineWidth(12)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_12.addWidget(self.line_2, 5, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem16, 7, 1, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_25.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_25.setText("")
        self.pushButton_25.setIcon(icon1)
        self.pushButton_25.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_12.addWidget(self.pushButton_25, 4, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_22.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_22.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_12.addWidget(self.pushButton_22, 3, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(240, 255, 255);")
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_10 = QtWidgets.QFrame(self.tab_6)
        self.frame_10.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_10)
        self.textBrowser_2.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QTextBrowser {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 15px;\n"
"}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_15.addWidget(self.textBrowser_2, 0, 1, 1, 1)
        self.listWidget_5 = QtWidgets.QListWidget(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_5.setFont(font)
        self.listWidget_5.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QListWidget {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"    background: rgba(255, 255, 255, 29);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.listWidget_5.setObjectName("listWidget_5")
        self.gridLayout_15.addWidget(self.listWidget_5, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_10, 0, 0, 7, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_20.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_20.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_9.addWidget(self.pushButton_20, 2, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem17, 5, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_21.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_21.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_9.addWidget(self.pushButton_21, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setMinimumSize(QtCore.QSize(40, 40))
        self.label_8.setMaximumSize(QtCore.QSize(40, 40))
        self.label_8.setStyleSheet("image: url(res/curseforge.png);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_8.setText("")
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_6)
        self.line_3.setMinimumSize(QtCore.QSize(0, 7))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(12)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_9.addWidget(self.line_3, 4, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_24.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_24.setText("")
        self.pushButton_24.setIcon(icon1)
        self.pushButton_24.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_9.addWidget(self.pushButton_24, 3, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_11 = QtWidgets.QFrame(self.tab_4)
        self.frame_11.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_11)
        self.textBrowser.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* COLOR */\n"
"QTextBrowser {\n"
"    background-color: rgb(0, 0, 0, 130);\n"
"    color: rgb(240, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    show-decoration-selected: none; /* make the selection span the entire width of the view */\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextBrowser::item:alternate {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser::item:selected {\n"
"    border: none;\n"
"    color: rgb(240, 255, 255);\n"
"    outline: none;\n"
"}\n"
"\n"
"QTextBrowser::item:selected:!active {\n"
"    background: none;\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser::item:selected:active {\n"
"    color: rgb(240, 255, 255);\n"
"}\n"
"\n"
"QTextBrowser::item:hover {\n"
"    background: rgba(255, 255, 255, 39);\n"
"    border: -2px solid rgb(0, 0, 0, 0);\n"
"    border-radius: 8px;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_17.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(185, 0))
        self.frame_2.setStyleSheet("background-color: rgba(49, 49, 49);")
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setVerticalSpacing(5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_18.setContentsMargins(0, 10, 6, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_3.setMinimumSize(QtCore.QSize(99, 29))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 14px;\n"
"    margin: -4px 2 -4px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: rgba(49, 49, 49, 140);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(C:/Users/студент.BestLaptop-ПК/Desktop/лаунчер/res/open.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 0px;\n"
"    left: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: none;\n"
"    border: 3px solid rgba(30, 30, 30);\n"
"    selection-background-color: rgba(255, 255, 255, 20);\n"
"    border-radius: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(59, 59, 59);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-bottom: 5px;\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_18.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_15.setMinimumSize(QtCore.QSize(37, 37))
        self.pushButton_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"image: url(res/USER.png);")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_18.addWidget(self.pushButton_15, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 4, 1, 1, 2)
        spacerItem18 = QtWidgets.QSpacerItem(0, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem18, 28, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem19, 22, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setMinimumSize(QtCore.QSize(0, 6))
        self.line.setLineWidth(89)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 9, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(200, 200, 200);")
        self.label.setIndent(9)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 29, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem20, 10, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("res/mods.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_14.setIcon(icon7)
        self.pushButton_14.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_7.addWidget(self.pushButton_14, 14, 1, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("res/minecraft_folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon8)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 12, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("res/новости.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon9)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 11, 1, 1, 2)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("res/новое.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_12.setIcon(icon10)
        self.pushButton_12.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_7.addWidget(self.pushButton_12, 23, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setSizeIncrement(QtCore.QSize(0, 18))
        self.pushButton_2.setBaseSize(QtCore.QSize(15, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("res/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon11)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 24, 1, 1, 2)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 3, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Minecraft:JAVA EDITION"))
        self.label_5.setText(_translate("MainWindow", "Отличный день для рыбалки!"))
        self.pushButton_4.setText(_translate("MainWindow", "ИГРАТЬ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Играть"))
        self.pushButton_10.setText(_translate("MainWindow", "+"))
        self.pushButton_16.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "Сборки"))
        self.label_6.setText(_translate("MainWindow", "Моды"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Сборки"))
        self.pushButton_23.setText(_translate("MainWindow", "+"))
        self.pushButton_22.setText(_translate("MainWindow", "–"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Версии"))
        self.pushButton_20.setText(_translate("MainWindow", "–"))
        self.pushButton_21.setText(_translate("MainWindow", "+"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Моды"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Установки"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Список изменений"))
        self.label.setText(_translate("MainWindow", "v.1.0-BETA"))
        self.pushButton_14.setText(_translate("MainWindow", "Модификации "))
        self.pushButton_3.setText(_translate("MainWindow", "Minecraft         "))
        self.pushButton.setText(_translate("MainWindow", "Новости          "))
        self.pushButton_12.setText(_translate("MainWindow", "Что нового    "))
        self.pushButton_2.setText(_translate("MainWindow", "Настройки     "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
