# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar {\n"
"    background-color: rgb(39, 39, 39);     \n"
"}\n"
"QTabBar::tab {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(200, 187, 179);\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(39, 39, 39);\n"
"    color: rgb(249, 249, 249);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, stop:0.01 rgb(30, 147, 10), stop:0.15 rgba(255, 255, 255, 0));\n"
"}")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background-color: rgba(0, 0, 0, 50);")
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 749, 577))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 15, 4, 1, 6)
        self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(85, 170, 0, 94);\n"
"border-radius: 9px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 19, 9, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(34, 34))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_6.addWidget(self.pushButton_8, 24, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 23, 0, 1, 10)
        self.pushButton_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setMinimumSize(QtCore.QSize(65, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(120, 255, 0, 94);\n"
"border-radius: 9px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 19, 8, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/comuniti.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(34, 34))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_6.addWidget(self.pushButton_9, 24, 9, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 10, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 9, 5, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setMinimumSize(QtCore.QSize(99, 27))
        self.comboBox.setMaximumSize(QtCore.QSize(56, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 14px;\n"
"    margin: -4px 2 -4px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: rgba(49, 49, 49, 140);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(C:/Users/студент.BestLaptop-ПК/Desktop/лаунчер/res/open.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 0px;\n"
"    left: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: none;\n"
"    border: 3px solid rgba(30, 30, 30);\n"
"    selection-background-color: rgba(255, 255, 255, 20);\n"
"    border-radius: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(59, 59, 59);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-bottom: 5px;\n"
"}")
        self.comboBox.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_6.addWidget(self.checkBox, 4, 0, 1, 10)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 14, 0, 1, 10)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(120, 255, 0, 94);\n"
"border-radius: 9px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 7, 9, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 10)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 3, 0, 1, 10)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 5, 0, 1, 10)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_6.addWidget(self.lineEdit, 7, 0, 1, 9)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_3.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid rgb(127, 127, 127);\n"
"    color: rgb(136, 136, 136);\n"
"    height: 8px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(89, 89, 89, 180);\n"
"    border: 2px solid rgb(129, 129, 129);\n"
"    width: 15px;\n"
"    margin: -2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.horizontalSlider_3.setMaximum(255)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout_6.addWidget(self.horizontalSlider_3, 10, 0, 1, 5)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_2.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid rgb(127, 127, 127);\n"
"    color: rgb(136, 136, 136);\n"
"    height: 8px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(89, 89, 89, 180);\n"
"    border: 2px solid rgb(129, 129, 129);\n"
"    width: 15px;\n"
"    margin: -2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_6.addWidget(self.horizontalSlider_2, 9, 0, 1, 5)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 8, 0, 1, 10)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_5.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid rgb(127, 127, 127);\n"
"    color: rgb(136, 136, 136);\n"
"    height: 8px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(89, 89, 89, 180);\n"
"    border: 2px solid rgb(129, 129, 129);\n"
"    width: 15px;\n"
"    margin: -2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.horizontalSlider_5.setMaximum(255)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.gridLayout_6.addWidget(self.horizontalSlider_5, 11, 0, 1, 5)
        self.horizontalSlider_4 = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_4.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid rgb(127, 127, 127);\n"
"    color: rgb(136, 136, 136);\n"
"    height: 8px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(89, 89, 89, 180);\n"
"    border: 2px solid rgb(129, 129, 129);\n"
"    width: 15px;\n"
"    margin: -2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.horizontalSlider_4.setMaximum(255)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.gridLayout_6.addWidget(self.horizontalSlider_4, 12, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 16, 0, 1, 10)
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 18, 0, 1, 5)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 11, 5, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_2.setMinimumSize(QtCore.QSize(99, 27))
        self.comboBox_2.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 14px;\n"
"    margin: -4px 2 -4px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border-radius: 10px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: rgba(49, 49, 49, 140);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(C:/Users/студент.BestLaptop-ПК/Desktop/лаунчер/res/open.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 0px;\n"
"    left: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    outline: none;\n"
"    border: 3px solid rgba(30, 30, 30);\n"
"    selection-background-color: rgba(255, 255, 255, 20);\n"
"    border-radius: 0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(59, 59, 59);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-bottom: 5px;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_6.addWidget(self.comboBox_2, 15, 0, 1, 2)
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 26))
        self.pushButton_7.setMaximumSize(QtCore.QSize(99, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(85, 170, 0, 94);\n"
"border-radius: 9px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_6.addWidget(self.pushButton_7, 25, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_6.addWidget(self.checkBox_2, 17, 0, 1, 5)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 12, 5, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_6.addWidget(self.lineEdit_2, 19, 0, 1, 8)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setMinimumSize(QtCore.QSize(99, 26))
        self.pushButton_10.setMaximumSize(QtCore.QSize(99, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(170, 0, 0, 124);\n"
"border-radius: 9px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_6.addWidget(self.pushButton_10, 25, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(85, 170, 0, 94);\n"
"border-radius: 9px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_6.addWidget(self.pushButton_6, 24, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 24, 1, 1, 7)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setMinimumSize(QtCore.QSize(74, 28))
        self.pushButton_2.setMaximumSize(QtCore.QSize(74, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(170, 0, 0, 124);\n"
"border-radius: 9px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 15, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setMinimumSize(QtCore.QSize(74, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(240, 255, 255);\n"
"background-color: rgba(85, 170, 0, 94);\n"
"border-radius: 9px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 15, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 20, 0, 1, 10)
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_6.addWidget(self.checkBox_5, 22, 0, 1, 2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_6.addWidget(self.checkBox_4, 21, 0, 1, 2)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_11.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/reboot.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_6.addWidget(self.pushButton_11, 12, 6, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_13.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 9, 6, 3, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("background-color: rgba(0, 0, 0, 50);")
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_2.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 767, 433))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setContentsMargins(-1, 9, -1, 50)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_10.addWidget(self.lineEdit_4, 6, 0, 1, 10)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 8, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_10.addWidget(self.lineEdit_3, 1, 0, 1, 10)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 5, 0, 1, 2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_10.addWidget(self.lineEdit_5, 7, 0, 1, 10)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 2, 0, 1, 2)
        self.spinBox_6 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_6.setFont(font)
        self.spinBox_6.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.spinBox_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_6.setMinimum(0)
        self.spinBox_6.setMaximum(8000)
        self.spinBox_6.setProperty("value", 1)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_10.addWidget(self.spinBox_6, 11, 9, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 10, 0, 1, 7)
        self.horizontalSlider_6 = QtWidgets.QSlider(self.scrollAreaWidgetContents_2)
        self.horizontalSlider_6.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid rgb(127, 127, 127);\n"
"    color: rgb(136, 136, 136);\n"
"    height: 8px;\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(89, 89, 89, 180);\n"
"    border: 2px solid rgb(129, 129, 129);\n"
"    width: 15px;\n"
"    margin: -2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.horizontalSlider_6.setMaximum(8000)
        self.horizontalSlider_6.setProperty("value", 1024)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.gridLayout_10.addWidget(self.horizontalSlider_6, 11, 0, 1, 8)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_10.addWidget(self.lineEdit_6, 9, 0, 1, 10)
        self.spinBox_4 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_4.sizePolicy().hasHeightForWidth())
        self.spinBox_4.setSizePolicy(sizePolicy)
        self.spinBox_4.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.spinBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(9999)
        self.spinBox_4.setProperty("value", 1)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_10.addWidget(self.spinBox_4, 3, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_12.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_12.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_10.addWidget(self.pushButton_12, 11, 8, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setStyleSheet("border-radius: 9px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 110);")
        self.spinBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setMaximum(9999)
        self.spinBox_5.setProperty("value", 1)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_10.addWidget(self.spinBox_5, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 3, 3, 1, 7)
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_10.addWidget(self.checkBox_6, 4, 0, 1, 2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("background-color: rgba(0, 0, 0, 50);")
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.tab_3)
        self.frame_4.setStyleSheet(".QFrame {\n"
"    border-image: url(res/baground/Default/9.JPG);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea_3.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    height: 17px;\n"
"    margin: 2px -18 2px -18;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    width: 26px;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(16, 16, 16);\n"
"    width: 18px;\n"
"    margin: -18px 2 -18px 2;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(60, 60, 60);\n"
"    min-height: 18px;\n"
"    border-radius: 5px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(70, 70, 70);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(79, 79, 79);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-top-left-radius: none;\n"
"    border-top-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: none;\n"
"    height: none;\n"
"    border-bottom-left-radius: none;\n"
"    border-bottom-right-radius: none;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: none;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: none;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_9.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Создать копию"))
        self.label_7.setText(_translate("MainWindow", "Поддержка"))
        self.pushButton_5.setText(_translate("MainWindow", "Обзор..."))
        self.label_10.setText(_translate("MainWindow", "G"))
        self.label_9.setText(_translate("MainWindow", "R"))
        self.comboBox.setItemText(0, _translate("MainWindow", "UA"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EN"))
        self.comboBox.setItemText(2, _translate("MainWindow", "RU"))
        self.checkBox.setText(_translate("MainWindow", "Изменение фона по дате и времени"))
        self.label_4.setText(_translate("MainWindow", "Профили"))
        self.pushButton.setText(_translate("MainWindow", "Обзор..."))
        self.label.setText(_translate("MainWindow", "Язык"))
        self.label_2.setText(_translate("MainWindow", "Фон"))
        self.label_5.setText(_translate("MainWindow", "Свой фон"))
        self.label_8.setText(_translate("MainWindow", "Цвет"))
        self.label_6.setText(_translate("MainWindow", "Обновления"))
        self.checkBox_3.setText(_translate("MainWindow", "Автоматическое создание резервной копии данных"))
        self.label_11.setText(_translate("MainWindow", "B"))
        self.pushButton_7.setText(_translate("MainWindow", "Сохранить"))
        self.checkBox_2.setText(_translate("MainWindow", "Автоматическое обновление"))
        self.label_12.setText(_translate("MainWindow", "A"))
        self.pushButton_10.setText(_translate("MainWindow", "Отмена"))
        self.pushButton_6.setText(_translate("MainWindow", "Нашли баг?"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.label_3.setText(_translate("MainWindow", "При запуске Minecraft:"))
        self.checkBox_5.setText(_translate("MainWindow", "Закрывать загрузчик"))
        self.checkBox_4.setText(_translate("MainWindow", "Закрывать лаунчер"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Настройки Лаунчера"))
        self.label_16.setText(_translate("MainWindow", "x"))
        self.label_18.setText(_translate("MainWindow", "Путь к Java"))
        self.label_14.setText(_translate("MainWindow", "Директория"))
        self.label_17.setText(_translate("MainWindow", "Аргументы"))
        self.label_15.setText(_translate("MainWindow", "Разрешение"))
        self.label_19.setText(_translate("MainWindow", "Выделение памяти"))
        self.checkBox_6.setText(_translate("MainWindow", "Полноэкранный режим"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Запуск Minecraft"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Настройки Minecraft"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
